output_path: '.'
output_file_name_prefix: testing

# Can be organization / folder / project w/ organization_number,
# folder_number and project number as the corresponding resource id.
root_resource_type: organization
root_resource_id: 5456546415

resource_structure:
  - resource_count: 1
    folder:
      - resource_count: 2
        folder:
          - resource_count: 10
            project:
              - resource_count: 5
                compute_firewall_rule: []
              - resource_count: 5
                compute_disk: []
              - resource_count: 15
                compute_snapshot: []
              - resource_count: 1
                appengine_application:
                  - resource_count: 5
                    appengine_service:
                      - resource_count: 5
                        appengine_version: []
              - resource_count: 15
                service_account: []
              - resource_count: 10
                bucket: []
              - resource_count: 5
                bigquery_dataset:
                  - resource_count: 100
                    bigquery_table: []
